### ISSUE TITLE
Build log

### ISSUE THREAD

**Issue by rickardcronholm** [adrianodennanni/tensorflow-1.12.0-cp37-cp37m-linux_x86_64#1]
Would you mind sharing the steps and version of dependencies? 

Im trying to build tf 1.12 on python 3.7.1 under Ubuntu 18.04 running on an ec2 instance. Cuda 10.0 is required, but Other than that im flexible.

I cant seem to ger around the protobuf issue

**Comment by adrianodennanni** [comment]
Sure, @rickardcronholm !
I cloned the repo from tensorflow `v1.12` branch and applied the git patches from Arch Linux repo, available here:
https://git.archlinux.org/svntogit/community.git/tree/trunk?h=packages/tensorflow

If you never applied a patch in a git repo, you can follow this tutorial: https://www.drupal.org/node/1399218

After that, you can compile the source.
